#!/usr/bin/env python3
"""Generate 640 additional diverse test statements."""
import csv

# Load existing 360
existing = []
with open('test_statements_1000.csv', 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    existing = list(reader)

print(f"Loaded {len(existing)} existing statements")

# Generate 640 new diverse statements
new_statements = []

# FACTUAL - Geography & Science (100 statements)
factual_claims = [
    ("The Statue of Liberty is in New York Harbor", "TRUE", "Factual_Easy", "Easy", "Famous landmark location"),
    ("London is the capital of England", "TRUE", "Factual_Easy", "Easy", "UK capital"),
    ("Australia is in Europe", "FALSE", "Factual_Easy", "Easy", "Continental location"),
    ("The Great Barrier Reef is in Australia", "TRUE", "Factual_Easy", "Easy", "Natural wonder location"),
    ("Mount Kilimanjaro is in Africa", "TRUE", "Factual_Easy", "Easy", "Mountain location"),
    ("The Sahara Desert is in Asia", "FALSE", "Factual_Easy", "Easy", "Desert misidentification"),
    ("The Amazon Rainforest is in South America", "TRUE", "Factual_Easy", "Easy", "Rainforest location"),
    ("Alaska is the largest US state by area", "TRUE", "Factual_Easy", "Easy", "State size fact"),
    ("Texas is larger than Alaska", "FALSE", "Factual_Easy", "Easy", "State comparison"),
    ("Hawaii is the newest US state", "TRUE", "Factual_Easy", "Easy", "Statehood chronology"),
    ("California has the largest US population", "TRUE", "Factual_Easy", "Easy", "Population fact"),
    ("The Dead Sea is the lowest point on Earth", "TRUE", "Factual_Easy", "Easy", "Elevation fact"),
    ("The Mariana Trench is the deepest ocean point", "TRUE", "Factual_Easy", "Easy", "Ocean depth"),
    ("Greenland is larger than Australia", "FALSE", "Factual_Easy", "Easy", "Land mass comparison"),
    ("The Andes is the longest mountain range", "TRUE", "Factual_Easy", "Easy", "Mountain range fact"),
    ("Mount Everest is in Nepal and Tibet", "TRUE", "Factual_Easy", "Easy", "Mountain border"),
    ("The Mediterranean Sea borders Africa", "TRUE", "Factual_Easy", "Easy", "Sea geography"),
    ("The Arctic Ocean is the largest ocean", "FALSE", "Factual_Easy", "Easy", "Ocean size"),
    ("China has the largest population", "TRUE", "Factual_Easy", "Easy", "Global population"),
    ("India is the largest country by area", "FALSE", "Factual_Easy", "Easy", "Country size"),
    ("The Panama Canal connects two oceans", "TRUE", "Factual_Easy", "Easy", "Canal function"),
    ("The Suez Canal is in South America", "FALSE", "Factual_Easy", "Easy", "Canal location"),
    ("Russia spans two continents", "TRUE", "Factual_Easy", "Easy", "Continental span"),
    ("Africa is the largest continent", "FALSE", "Factual_Easy", "Easy", "Continent size"),
    ("The Congo River is in South America", "FALSE", "Factual_Easy", "Easy", "River location"),
    ("Lake Superior is the largest Great Lake", "TRUE", "Factual_Easy", "Easy", "Lake size"),
    ("The Mississippi River flows north", "FALSE", "Factual_Easy", "Easy", "River direction"),
    ("New York City has five boroughs", "TRUE", "Factual_Easy", "Easy", "City structure"),
    ("Los Angeles is the capital of California", "FALSE", "Factual_Easy", "Easy", "State capital"),
    ("Washington DC is a US state", "FALSE", "Factual_Easy", "Easy", "District status"),
    ("Puerto Rico is a US state", "FALSE", "Factual_Easy", "Easy", "Territory status"),
    ("Canada has 10 provinces", "TRUE", "Factual_Easy", "Easy", "Provincial count"),
    ("Mexico City is the capital of Mexico", "TRUE", "Factual_Easy", "Easy", "National capital"),
    ("The equator passes through Ecuador", "TRUE", "Factual_Easy", "Easy", "Latitude fact"),
    ("The North Pole is in Canada", "FALSE", "Factual_Easy", "Easy", "Polar location"),
    ("Antarctica is a country", "FALSE", "Factual_Easy", "Easy", "Continental status"),
    ("The International Date Line is at 180 degrees", "TRUE", "Factual_Easy", "Easy", "Time zone fact"),
    ("Greenwich Mean Time is based in London", "TRUE", "Factual_Easy", "Easy", "Time standard"),
    ("Oxygen makes up most of Earth's atmosphere", "FALSE", "Factual_Easy", "Easy", "Atmospheric composition"),
    ("Nitrogen is the most abundant gas in air", "TRUE", "Factual_Easy", "Easy", "Air composition"),
    ("Water freezes at 0 degrees Celsius", "TRUE", "Factual_Easy", "Easy", "Freezing point"),
    ("Water boils at 200 degrees Celsius at sea level", "FALSE", "Factual_Easy", "Easy", "Boiling point"),
    ("Sound travels faster in water than air", "TRUE", "Scientific", "Medium", "Sound propagation"),
    ("Light travels at infinite speed", "FALSE", "Scientific", "Medium", "Light speed"),
    ("The speed of sound is about 343 meters per second", "TRUE", "Scientific", "Medium", "Sound speed"),
    ("Absolute zero is 0 degrees Celsius", "FALSE", "Scientific", "Medium", "Temperature scale"),
    ("Diamond is the hardest natural material", "TRUE", "Scientific", "Medium", "Material hardness"),
    ("Gold is heavier than lead", "TRUE", "Scientific", "Medium", "Metal density"),
    ("Iron is magnetic", "TRUE", "Scientific", "Medium", "Magnetic property"),
    ("Copper is a good conductor of electricity", "TRUE", "Scientific", "Medium", "Electrical conductivity"),
    # Adding 50 more factual to reach 100
    ("The aurora borealis occurs in the southern hemisphere", "FALSE", "Factual_Easy", "Easy", "Aurora location"),
    ("Earthquakes are measured on the Richter scale", "TRUE", "Scientific", "Medium", "Seismic measurement"),
    ("Hurricanes and typhoons are the same phenomenon", "TRUE", "Scientific", "Medium", "Storm classification"),
    ("Tornadoes only occur in the United States", "FALSE", "Scientific", "Medium", "Weather geography"),
    ("The Coriolis effect influences hurricane rotation", "TRUE", "Scientific", "Medium", "Atmospheric physics"),
    ("Lightning is hotter than the surface of the sun", "TRUE", "Scientific", "Medium", "Temperature comparison"),
    ("Thunder is caused by lightning", "TRUE", "Scientific", "Medium", "Weather causation"),
    ("Rain is caused by clouds sweating", "FALSE", "Scientific", "Medium", "Precipitation mechanism"),
    ("Snow is frozen rain", "FALSE", "Scientific", "Medium", "Snow formation"),
    ("Hail forms in thunderstorms", "TRUE", "Scientific", "Medium", "Hail formation"),
    ("The greenhouse effect warms Earth", "TRUE", "Scientific", "Medium", "Climate science"),
    ("CO2 is a greenhouse gas", "TRUE", "Scientific", "Medium", "Atmospheric chemistry"),
    ("Ozone protects from UV radiation", "TRUE", "Scientific", "Medium", "Atmospheric protection"),
    ("The ozone layer is in the stratosphere", "TRUE", "Scientific", "Medium", "Atmospheric layers"),
    ("Clouds are made of water vapor", "TRUE", "Scientific", "Medium", "Cloud composition"),
    ("Fog is a cloud at ground level", "TRUE", "Scientific", "Medium", "Fog definition"),
    ("Dew forms from condensation", "TRUE", "Scientific", "Medium", "Dew formation"),
    ("Frost is frozen dew", "FALSE", "Scientific", "Medium", "Frost formation"),
    ("The moon causes ocean tides", "TRUE", "Scientific", "Medium", "Tidal forces"),
    ("The sun is a planet", "FALSE", "Factual_Easy", "Easy", "Celestial classification"),
    ("The sun is a star", "TRUE", "Factual_Easy", "Easy", "Solar classification"),
    ("Earth orbits the sun", "TRUE", "Factual_Easy", "Easy", "Orbital mechanics"),
    ("The moon orbits Earth", "TRUE", "Factual_Easy", "Easy", "Lunar orbit"),
    ("Mars is called the Red Planet", "TRUE", "Factual_Easy", "Easy", "Planetary nickname"),
    ("Venus is the hottest planet", "TRUE", "Scientific", "Medium", "Planetary temperature"),
    ("Mercury is closest to the sun", "TRUE", "Factual_Easy", "Easy", "Planetary order"),
    ("Neptune is the farthest planet", "TRUE", "Factual_Easy", "Easy", "Planetary distance"),
    ("Pluto is still classified as a planet", "FALSE", "Factual_Easy", "Easy", "Planetary status"),
    ("Saturn has rings", "TRUE", "Factual_Easy", "Easy", "Planetary feature"),
    ("All gas giants have rings", "TRUE", "Scientific", "Medium", "Planetary rings"),
    ("The asteroid belt is between Mars and Jupiter", "TRUE", "Scientific", "Medium", "Solar system structure"),
    ("Comets have tails", "TRUE", "Factual_Easy", "Easy", "Comet features"),
    ("Meteors are shooting stars", "TRUE", "Factual_Easy", "Easy", "Meteor terminology"),
    ("The Milky Way is our galaxy", "TRUE", "Factual_Easy", "Easy", "Galactic identity"),
    ("Black holes emit light", "FALSE", "Scientific", "Medium", "Black hole physics"),
    ("The Big Bang created the universe", "TRUE", "Scientific", "Medium", "Cosmology theory"),
    ("The universe is expanding", "TRUE", "Scientific", "Medium", "Cosmological expansion"),
    ("Stars are made mostly of hydrogen", "TRUE", "Scientific", "Medium", "Stellar composition"),
    ("The sun will become a black hole", "FALSE", "Scientific", "Medium", "Stellar evolution"),
    ("Supernovas create heavy elements", "TRUE", "Scientific", "Medium", "Nuclear synthesis"),
    ("Neutron stars are incredibly dense", "TRUE", "Scientific", "Medium", "Stellar density"),
    ("Light years measure time", "FALSE", "Scientific", "Medium", "Astronomical units"),
    ("Parsecs measure distance", "TRUE", "Scientific", "Medium", "Astronomical measurement"),
    ("The closest star to Earth is Proxima Centauri", "FALSE", "Factual_Easy", "Easy", "Stellar proximity"),
    ("The sun is the closest star to Earth", "TRUE", "Factual_Easy", "Easy", "Solar proximity"),
    ("Constellations are actual star groupings", "FALSE", "Scientific", "Medium", "Constellation nature"),
    ("The North Star is the brightest star", "FALSE", "Factual_Easy", "Easy", "Star brightness"),
    ("Sirius is the brightest star in the night sky", "TRUE", "Factual_Easy", "Easy", "Star visibility"),
    ("The moon has its own light", "FALSE", "Factual_Easy", "Easy", "Lunar illumination"),
    ("Solar eclipses occur when the moon blocks the sun", "TRUE", "Factual_Easy", "Easy", "Eclipse mechanism"),
]

# HISTORICAL CLAIMS (120 statements)
historical_claims = [
    ("World War I ended in 1918", "TRUE", "Historical", "Medium", "War timeline"),
    ("The Cold War was a military conflict", "FALSE", "Historical", "Medium", "Conflict classification"),
    ("The Berlin Wall fell in 1989", "TRUE", "Historical", "Medium", "Historic event date"),
    ("The Moon landing happened in 1969", "TRUE", "Historical", "Medium", "Space milestone"),
    ("The Renaissance began in Italy", "TRUE", "Historical", "Medium", "Cultural movement origin"),
    ("The printing press was invented in China", "FALSE", "Historical", "Medium", "Invention attribution"),
    ("Gutenberg invented the printing press", "TRUE", "Historical", "Medium", "Invention credit"),
    ("The Industrial Revolution started in England", "TRUE", "Historical", "Medium", "Economic revolution origin"),
    ("The Wright brothers flew the first airplane", "TRUE", "Historical", "Medium", "Aviation milestone"),
    ("Henry Ford invented the automobile", "FALSE", "Historical", "Medium", "Invention misattribution"),
    ("The telephone was invented by Alexander Graham Bell", "TRUE", "Historical", "Medium", "Communication invention"),
    ("The light bulb was invented by Thomas Edison", "FALSE", "Historical", "Medium", "Edison improved existing design"),
    ("Penicillin was discovered by Alexander Fleming", "TRUE", "Historical", "Medium", "Medical discovery"),
    ("The Theory of Relativity was developed by Einstein", "TRUE", "Historical", "Medium", "Scientific theory"),
    ("Isaac Newton discovered gravity", "TRUE", "Historical", "Medium", "Physics discovery"),
    ("Galileo invented the telescope", "FALSE", "Historical", "Medium", "Telescope attribution"),
    ("The Magna Carta was signed in 1215", "TRUE", "Historical", "Medium", "Historic document date"),
    ("The American Revolution ended in 1783", "TRUE", "Historical", "Medium", "Revolution timeline"),
    ("The French Revolution started in 1789", "TRUE", "Historical", "Medium", "Revolution date"),
    ("Napoleon was defeated at Waterloo", "TRUE", "Historical", "Medium", "Battle outcome"),
    # Continue with 100 more historical claims...
    ("Julius Caesar was the first Roman Emperor", "FALSE", "Historical", "Medium", "Augustus was first emperor"),
    ("The Roman Empire fell in 476 AD", "TRUE", "Historical", "Medium", "Empire collapse date"),
    ("The Byzantine Empire was the eastern Roman Empire", "TRUE", "Historical", "Medium", "Empire continuity"),
    ("Genghis Khan founded the Mongol Empire", "TRUE", "Historical", "Medium", "Empire founding"),
    ("The Silk Road connected Europe and Asia", "TRUE", "Historical", "Medium", "Trade route"),
    ("Marco Polo visited China", "TRUE", "Historical", "Medium", "Explorer journey"),
    ("Christopher Columbus reached Asia", "FALSE", "Historical", "Medium", "Exploration misunderstanding"),
    ("Magellan's expedition circumnavigated the globe", "TRUE", "Historical", "Medium", "Global exploration"),
    ("The Spanish Armada was defeated by England", "TRUE", "Historical", "Medium", "Naval battle"),
    ("Joan of Arc was French", "TRUE", "Historical", "Medium", "National identity"),
    ("The Black Death occurred in the 14th century", "TRUE", "Historical", "Medium", "Pandemic timeline"),
    ("The Hundred Years War lasted 100 years", "FALSE", "Historical", "Medium", "Actually lasted 116 years"),
    ("Shakespeare wrote during the Elizabethan era", "TRUE", "Historical", "Medium", "Literary period"),
    ("The Sistine Chapel ceiling was painted by Michelangelo", "TRUE", "Historical", "Medium", "Artistic achievement"),
    ("Leonardo da Vinci painted the Mona Lisa", "TRUE", "Historical", "Medium", "Artistic masterpiece"),
    ("Van Gogh cut off his entire ear", "FALSE", "Historical", "Medium", "Only part of ear"),
    ("The Eiffel Tower was built for the 1889 World's Fair", "TRUE", "Historical", "Medium", "Structure purpose"),
    ("The Statue of Liberty was a gift from France", "TRUE", "Historical", "Medium", "Monument origin"),
    ("The Great Wall of China was built to keep out Mongols", "TRUE", "Historical", "Medium", "Wall purpose"),
    ("The Taj Mahal was built as a tomb", "TRUE", "Historical", "Medium", "Monument purpose"),
    ("Stonehenge was built by the Druids", "FALSE", "Historical", "Medium", "Predates Druids"),
    ("The Rosetta Stone helped decipher hieroglyphics", "TRUE", "Historical", "Medium", "Translation breakthrough"),
    ("Cleopatra was Greek", "TRUE", "Historical", "Medium", "Ptolemaic dynasty"),
    ("The Library of Alexandria was burned down", "TRUE", "Historical", "Medium", "Historic destruction"),
    ("Pompeii was buried by Mount Vesuvius", "TRUE", "Historical", "Medium", "Volcanic destruction"),
    ("The Colosseum was used for gladiator fights", "TRUE", "Historical", "Medium", "Arena purpose"),
    ("Ancient Romans had concrete", "TRUE", "Historical", "Medium", "Construction material"),
    ("The Parthenon is in Rome", "FALSE", "Historical", "Medium", "It's in Athens"),
    ("Democracy originated in ancient Greece", "TRUE", "Historical", "Medium", "Political system origin"),
    ("The Olympic Games started in ancient Greece", "TRUE", "Historical", "Medium", "Athletic tradition"),
    ("Alexander the Great conquered Persia", "TRUE", "Historical", "Medium", "Military conquest"),
    ("Cleopatra lived closer to the moon landing than the pyramids", "TRUE", "Historical", "Medium", "Timeline perspective"),
    ("The first university was in Bologna", "TRUE", "Historical", "Medium", "Educational institution"),
    ("The printing press came before the Renaissance", "FALSE", "Historical", "Medium", "Chronological order"),
    ("The Crusades were fought over Jerusalem", "TRUE", "Historical", "Medium", "Religious wars"),
    ("The Ottoman Empire controlled Constantinople", "TRUE", "Historical", "Medium", "Imperial capital"),
    ("The Dutch East India Company was the first corporation", "TRUE", "Historical", "Medium", "Corporate history"),
    ("The Louisiana Purchase doubled US territory", "TRUE", "Historical", "Medium", "Territorial expansion"),
    ("The Alamo is in Texas", "TRUE", "Historical", "Medium", "Historic site"),
    ("The transcontinental railroad connected US coasts", "TRUE", "Historical", "Medium", "Transportation milestone"),
    ("The California Gold Rush was in 1849", "TRUE", "Historical", "Medium", "Economic event"),
    ("The Pony Express operated for decades", "FALSE", "Historical", "Medium", "Only 18 months"),
    ("Ellis Island was an immigration station", "TRUE", "Historical", "Medium", "Immigration history"),
    ("The Statue of Liberty faces the ocean", "FALSE", "Historical", "Medium", "Faces harbor"),
    ("Pearl Harbor led to US entry into WWII", "TRUE", "Historical", "Medium", "War catalyst"),
    ("D-Day was the largest amphibious invasion", "TRUE", "Historical", "Medium", "Military operation"),
    ("The atomic bomb ended WWII", "TRUE", "Historical", "Medium", "War conclusion"),
    ("The Holocaust killed six million Jews", "TRUE", "Historical", "Medium", "Genocide scale"),
    ("Anne Frank wrote a diary during WWII", "TRUE", "Historical", "Medium", "Historical document"),
    ("The Nuremberg Trials prosecuted Nazi leaders", "TRUE", "Historical", "Medium", "War crimes tribunal"),
    ("The Marshall Plan helped rebuild Europe", "TRUE", "Historical", "Medium", "Post-war recovery"),
    ("NATO was formed after WWII", "TRUE", "Historical", "Medium", "Military alliance"),
    ("The United Nations was founded in 1945", "TRUE", "Historical", "Medium", "International organization"),
    ("The Korean War ended in 1953", "TRUE", "Historical", "Medium", "Conflict timeline"),
    ("The Vietnam War ended in 1975", "TRUE", "Historical", "Medium", "War conclusion"),
    ("The Cuban Missile Crisis almost caused nuclear war", "TRUE", "Historical", "Medium", "Cold War crisis"),
    ("JFK was assassinated in Dallas", "TRUE", "Historical", "Medium", "Presidential assassination"),
    ("Martin Luther King Jr. gave the 'I Have a Dream' speech", "TRUE", "Historical", "Medium", "Civil rights milestone"),
    ("Rosa Parks refused to give up her bus seat", "TRUE", "Historical", "Medium", "Civil rights protest"),
    ("The Civil Rights Act was passed in 1964", "TRUE", "Historical", "Medium", "Legislative milestone"),
    ("Nelson Mandela became South African president", "TRUE", "Historical", "Medium", "Political achievement"),
    ("Apartheid ended in South Africa in the 1990s", "TRUE", "Historical", "Medium", "System dismantling"),
    ("The Chernobyl disaster occurred in 1986", "TRUE", "Historical", "Medium", "Nuclear accident"),
    ("The Space Shuttle Challenger exploded in 1986", "TRUE", "Historical", "Medium", "Spaceflight disaster"),
    ("The Hubble Telescope was launched in 1990", "TRUE", "Historical", "Medium", "Space observation"),
    ("The internet was invented by the military", "TRUE", "Historical", "Medium", "ARPANET origins"),
    ("Tim Berners-Lee invented the World Wide Web", "TRUE", "Historical", "Medium", "Web creation"),
    ("The dot-com bubble burst in 2000", "TRUE", "Historical", "Medium", "Economic crash"),
    ("The September 11 attacks occurred in 2001", "TRUE", "Historical", "Medium", "Terrorist attack"),
    ("The War in Afghanistan started in 2001", "TRUE", "Historical", "Medium", "Military conflict"),
    ("The Iraq War began in 2003", "TRUE", "Historical", "Medium", "Military invasion"),
    ("Hurricane Katrina devastated New Orleans in 2005", "TRUE", "Historical", "Medium", "Natural disaster"),
    ("The Great Recession started in 2008", "TRUE", "Historical", "Medium", "Economic crisis"),
    ("Barack Obama was the first Black US president", "TRUE", "Historical", "Medium", "Presidential milestone"),
    ("The Arab Spring began in 2010", "TRUE", "Historical", "Medium", "Political movement"),
    ("Osama bin Laden was killed in 2011", "TRUE", "Historical", "Medium", "Military operation"),
    ("The Syrian Civil War started in 2011", "TRUE", "Historical", "Medium", "Ongoing conflict"),
    ("Brexit referendum passed in 2016", "TRUE", "Historical", "Medium", "Political vote"),
    ("Donald Trump was elected president in 2016", "TRUE", "Historical", "Medium", "Electoral outcome"),
    ("COVID-19 pandemic began in 2019", "TRUE", "Current_Events", "Easy", "Global health crisis"),
    ("George Floyd's death sparked protests in 2020", "TRUE", "Current_Events", "Easy", "Social justice movement"),
    ("Joe Biden won the 2020 election", "TRUE", "Current_Events", "Easy", "Electoral outcome"),
    ("The Taliban retook Afghanistan in 2021", "TRUE", "Current_Events", "Easy", "Political change"),
    ("Russia invaded Ukraine in 2022", "TRUE", "Current_Events", "Easy", "Military conflict"),
    ("Queen Elizabeth II died in 2022", "TRUE", "Current_Events", "Easy", "Monarchical succession"),
    ("King Charles III became British monarch in 2022", "TRUE", "Current_Events", "Easy", "Royal succession"),
    ("Elon Musk bought Twitter in 2022", "TRUE", "Current_Events", "Easy", "Corporate acquisition"),
    ("ChatGPT was released in November 2022", "TRUE", "Current_Events", "Easy", "AI milestone"),
    ("The James Webb Telescope launched in 2021", "TRUE", "Current_Events", "Easy", "Space exploration"),
    ("SpaceX successfully landed reusable rockets", "TRUE", "Current_Events", "Easy", "Aerospace achievement"),
    ("Tesla became the most valuable car company", "TRUE", "Current_Events", "Easy", "Market valuation"),
    ("Bitcoin reached $60,000 in 2021", "TRUE", "Current_Events", "Easy", "Cryptocurrency peak"),
    ("Facebook changed its name to Meta", "TRUE", "Current_Events", "Easy", "Corporate rebranding"),
    ("TikTok became the most downloaded app", "TRUE", "Current_Events", "Easy", "Social media dominance"),
    ("The metaverse became a tech buzzword", "TRUE", "Current_Events", "Easy", "Technology trend"),
    ("NFTs became popular in 2021", "TRUE", "Current_Events", "Easy", "Digital asset trend"),
    ("Cryptocurrency crashed in 2022", "TRUE", "Current_Events", "Easy", "Market decline"),
    ("AI image generation became mainstream in 2022", "TRUE", "Current_Events", "Easy", "AI advancement"),
    ("Climate protests increased globally", "TRUE", "Current_Events", "Easy", "Environmental activism"),
]

# SCIENTIFIC MYTHS (100 statements)
scientific_myths = [
    ("Lightning never strikes twice in the same place", "FALSE", "Scientific", "Medium", "Common misconception"),
    ("You lose most body heat through your head", "FALSE", "Myths", "Medium", "Proportional to surface area"),
    ("Cracking knuckles causes arthritis", "FALSE", "Myths", "Medium", "No proven link"),
    ("Swallowed gum stays in stomach for 7 years", "FALSE", "Myths", "Medium", "Passes through normally"),
    ("We only use 10% of our brains", "FALSE", "Scientific", "Medium", "Entire brain is active"),
    ("Sugar makes kids hyperactive", "FALSE", "Myths", "Medium", "No consistent evidence"),
    ("Carrots improve your night vision", "FALSE", "Myths", "Medium", "WWII propaganda"),
    ("Reading in dim light damages eyes", "FALSE", "Myths", "Medium", "Causes strain only"),
    ("Shaving makes hair grow back thicker", "FALSE", "Myths", "Medium", "Optical illusion"),
    ("You need 8 glasses of water daily", "FALSE", "Myths", "Medium", "No scientific basis for exact amount"),
    ("Microwaves cause cancer", "FALSE", "Scientific", "Medium", "Non-ionizing radiation"),
    ("Vaccines cause autism", "FALSE", "Scientific", "Medium", "Thoroughly debunked"),
    ("Organic food is more nutritious", "FALSE", "Scientific", "Medium", "Nutritional value similar"),
    ("GMOs are dangerous", "FALSE", "Scientific", "Medium", "Scientific consensus: safe"),
    ("MSG is harmful", "FALSE", "Scientific", "Medium", "No scientific evidence"),
    ("Detox diets cleanse toxins", "FALSE", "Scientific", "Medium", "Liver and kidneys do this"),
    ("Alkaline water is healthier", "FALSE", "Scientific", "Medium", "Body regulates pH"),
    ("Antioxidants prevent cancer", "FALSE", "Scientific", "Medium", "Oversimplified claim"),
    ("Vitamin C prevents colds", "FALSE", "Scientific", "Medium", "May reduce duration slightly"),
    ("Antibiotics work on viruses", "FALSE", "Scientific", "Medium", "Only work on bacteria"),
    # Continue with 80 more scientific myths...
    ("You can see the Great Wall from space", "FALSE", "Myths", "Medium", "Too narrow"),
    ("Different tongue parts taste different flavors", "FALSE", "Myths", "Medium", "Debunked taste map"),
    ("Goldfish have 3-second memory", "FALSE", "Myths", "Medium", "Can remember for months"),
    ("Bulls are enraged by red color", "FALSE", "Myths", "Medium", "Colorblind to red"),
    ("Bats are blind", "FALSE", "Myths", "Medium", "They can see"),
    ("Ostriches bury heads in sand", "FALSE", "Myths", "Medium", "They dig nests"),
    ("Lemmings commit mass suicide", "FALSE", "Myths", "Medium", "Disney faked it"),
    ("Chameleons change color to match surroundings", "FALSE", "Myths", "Medium", "Change for temp/mood"),
    ("Touching baby birds makes parents abandon them", "FALSE", "Myths", "Medium", "Birds have poor smell"),
    ("Daddy longlegs are most venomous spiders", "FALSE", "Myths", "Medium", "Not even spiders"),
    ("Bumblebees shouldn't be able to fly", "FALSE", "Myths", "Medium", "Outdated aerodynamics"),
    ("Glass is a slow-moving liquid", "FALSE", "Myths", "Medium", "Amorphous solid"),
    ("Medieval people thought Earth was flat", "FALSE", "Historical", "Medium", "Educated knew round"),
    ("Columbus proved Earth was round", "FALSE", "Historical", "Medium", "Already known"),
    ("Humans evolved from monkeys", "FALSE", "Scientific", "Medium", "Common ancestor"),
    ("Neanderthals were primitive", "FALSE", "Scientific", "Medium", "Had complex culture"),
    ("Dinosaurs and humans coexisted", "FALSE", "Scientific", "Medium", "65 million years apart"),
    ("T-Rex arms were useless", "FALSE", "Scientific", "Medium", "Had functional purpose"),
    ("All dinosaurs were reptiles", "FALSE", "Scientific", "Medium", "Birds are dinosaurs"),
    ("Pterodactyls were dinosaurs", "FALSE", "Scientific", "Medium", "Flying reptiles, not dinosaurs"),
    ("Dinosaurs were cold-blooded", "FALSE", "Scientific", "Medium", "Evidence suggests warm-blooded"),
    ("Asteroid killed all dinosaurs instantly", "FALSE", "Scientific", "Medium", "Took thousands of years"),
    ("Neanderthals couldn't speak", "FALSE", "Scientific", "Medium", "Had language capability"),
    ("Cave people lived in caves", "FALSE", "Historical", "Medium", "Mostly lived outside"),
    ("Vikings had horned helmets", "FALSE", "Historical", "Medium", "Romantic myth"),
    ("Medieval armor was too heavy to move", "FALSE", "Historical", "Medium", "Well-balanced design"),
    ("Knights rescued damsels in distress", "FALSE", "Historical", "Medium", "Literary invention"),
    ("Witches were burned in Salem", "FALSE", "Historical", "Medium", "They were hanged"),
    ("Iron maiden was medieval torture device", "FALSE", "Historical", "Medium", "19th century invention"),
    ("Chastity belts were used in Crusades", "FALSE", "Historical", "Medium", "Victorian myth"),
    ("Napoleon was very short", "FALSE", "Historical", "Medium", "Average height for time"),
    ("George Washington had wooden teeth", "FALSE", "Historical", "Medium", "Ivory, bone, lead"),
    ("Benjamin Franklin discovered electricity", "FALSE", "Historical", "Medium", "Studied it, didn't discover"),
    ("Einstein failed math", "FALSE", "Historical", "Medium", "Excelled at math"),
    ("Nero fiddled while Rome burned", "FALSE", "Historical", "Medium", "Fiddles didn't exist"),
    ("Marie Antoinette said 'Let them eat cake'", "FALSE", "Historical", "Medium", "No evidence"),
    ("Mussolini made trains run on time", "FALSE", "Historical", "Medium", "Propaganda myth"),
    ("The pyramids were built by slaves", "FALSE", "Historical", "Medium", "Paid workers"),
    ("Cleopatra was Egyptian ethnically", "FALSE", "Historical", "Medium", "Greek Macedonian"),
    ("Julius Caesar was born by C-section", "FALSE", "Historical", "Medium", "Mother lived after birth"),
    ("Paul Revere shouted 'The British are coming'", "FALSE", "Historical", "Medium", "Colonists were British"),
    ("Cowboys wore cowboy hats", "FALSE", "Historical", "Medium", "Bowler hats more common"),
    ("Wild West had frequent shootouts", "FALSE", "Historical", "Medium", "Mostly peaceful"),
    ("Pirates made people walk the plank", "FALSE", "Historical", "Medium", "Rare or fictional"),
    ("Pirates buried treasure", "FALSE", "Historical", "Medium", "Usually spent it"),
    ("Vikings discovered America first", "TRUE", "Historical", "Medium", "Before Columbus"),
    ("Leif Erikson reached North America", "TRUE", "Historical", "Medium", "Around 1000 AD"),
    ("The Pinta, Nina, and Santa Maria were large ships", "FALSE", "Historical", "Medium", "Relatively small"),
    ("Pocahontas saved John Smith", "FALSE", "Historical", "Medium", "Likely fabricated"),
    ("Pocahontas married John Smith", "FALSE", "Historical", "Medium", "Married John Rolfe"),
    ("Thanksgiving was always in November", "FALSE", "Historical", "Medium", "Date changed over time"),
    ("Pilgrims wore black and white", "FALSE", "Historical", "Medium", "Wore colorful clothes"),
    ("Pilgrims and Native Americans were friends", "FALSE", "Historical", "Medium", "Complex relationship"),
    ("Native Americans didn't use the wheel", "FALSE", "Historical", "Medium", "Used in toys"),
    ("Columbus discovered tobacco", "FALSE", "Historical", "Medium", "Native Americans already used it"),
    ("Tomatoes were thought poisonous in Europe", "TRUE", "Historical", "Medium", "Initially mistrusted"),
    ("Potatoes caused Irish famine", "FALSE", "Historical", "Medium", "Potato blight did"),
    ("Tea caused Boston Tea Party", "TRUE", "Historical", "Medium", "Tax protest"),
    ("Shot heard round the world was literal", "FALSE", "Historical", "Medium", "Metaphorical phrase"),
    ("Declaration signed on July 4th", "FALSE", "Historical", "Medium", "Adopted July 4, signed August 2"),
    ("Liberty Bell cracked on July 4th", "FALSE", "Historical", "Medium", "Cracked later"),
    ("Betsy Ross designed the flag", "FALSE", "Historical", "Medium", "Likely apocryphal"),
    ("Star Spangled Banner written during War of 1812", "TRUE", "Historical", "Medium", "Fort McHenry"),
    ("White House was always white", "FALSE", "Historical", "Medium", "Painted white after burning"),
    ("Lincoln wrote Gettysburg Address on envelope", "FALSE", "Historical", "Medium", "Prepared in advance"),
    ("Lincoln freed all slaves with Emancipation", "FALSE", "Historical", "Medium", "Only Confederate states"),
    ("Civil War was only about slavery", "FALSE", "Historical", "Medium", "Complex causes"),
    ("Grant was a drunk", "FALSE", "Historical", "Medium", "Exaggerated by opponents"),
    ("Lee owned slaves reluctantly", "FALSE", "Historical", "Medium", "He defended slavery"),
    ("Reconstruction succeeded", "FALSE", "Historical", "Medium", "Ultimately failed"),
    ("Jim Crow laws were unofficial", "FALSE", "Historical", "Medium", "State-enforced segregation"),
]

# LOGIC & REASONING (100 statements)
logic_claims = [
    ("If all cats are mammals, and all mammals breathe, then all cats breathe", "TRUE", "Logic_Reasoning", "Hard", "Valid syllogism"),
    ("Some doctors are rich, some rich are unhappy, so some doctors are unhappy", "FALSE", "Logic_Reasoning", "Hard", "Invalid syllogism"),
    ("You're either with us or against us", "FALSE", "Logic_Reasoning", "Hard", "False dichotomy"),
    ("My father has two sons and I have two brothers", "FALSE", "Logic_Reasoning", "Hard", "You are one of two sons"),
    ("My sister has three brothers, I have two brothers", "FALSE", "Logic_Reasoning", "Hard", "You are one of three"),
    ("If A=B and B=C then A=C", "TRUE", "Logic_Reasoning", "Hard", "Transitive property"),
    ("Successful people wake early, I wake early, so I'll succeed", "FALSE", "Logic_Reasoning", "Hard", "Affirming consequent"),
    ("All ravens are black, this is black, so it's a raven", "FALSE", "Logic_Reasoning", "Hard", "Inverse error"),
    ("Can't prove aliens don't exist, so they must exist", "FALSE", "Logic_Reasoning", "Hard", "Appeal to ignorance"),
    ("Everyone I know likes pizza, so everyone likes pizza", "FALSE", "Logic_Reasoning", "Hard", "Hasty generalization"),
    ("More firefighters at fires cause more damage", "FALSE", "Logic_Reasoning", "Hard", "Correlation not causation"),
    ("We've always done it this way, so it's right", "FALSE", "Logic_Reasoning", "Hard", "Appeal to tradition"),
    ("This worked for me, so it works for everyone", "FALSE", "Logic_Reasoning", "Hard", "Anecdotal evidence"),
    ("If we allow X, then Y will happen", "FALSE", "Logic_Reasoning", "Hard", "Slippery slope"),
    ("No one proved it false, so it's true", "FALSE", "Logic_Reasoning", "Hard", "Burden of proof"),
    ("If A then B. B happened. Therefore A caused B.", "FALSE", "Logic_Reasoning", "Hard", "Post hoc fallacy"),
    ("Either increase taxes or cut services", "FALSE", "Logic_Reasoning", "Hard", "False dilemma"),
    ("Most people believe X, so X is true", "FALSE", "Logic_Reasoning", "Hard", "Appeal to popularity"),
    ("Expert says X, so X must be true", "FALSE", "Logic_Reasoning", "Hard", "Appeal to authority"),
    ("X happened after Y, so Y caused X", "FALSE", "Logic_Reasoning", "Hard", "Post hoc ergo propter hoc"),
    # 80 more logic problems to add...
    ("If it rains, ground is wet. Ground is wet, so it rained.", "FALSE", "Logic_Reasoning", "Hard", "Affirming consequent"),
    ("All dogs bark. Fido barks. So Fido is a dog.", "FALSE", "Logic_Reasoning", "Hard", "Affirming consequent"),
    ("If you study, you pass. You passed. So you studied.", "FALSE", "Logic_Reasoning", "Hard", "Affirming consequent"),
    ("No cats are dogs. Some pets are cats. So some pets aren't dogs.", "TRUE", "Logic_Reasoning", "Hard", "Valid syllogism"),
    ("All squares are rectangles. This is a square. So it's a rectangle.", "TRUE", "Logic_Reasoning", "Hard", "Valid deduction"),
    ("If today is Monday, tomorrow is Tuesday. Today is Monday.", "TRUE", "Logic_Reasoning", "Hard", "Modus ponens"),
    ("If raining, I bring umbrella. I brought umbrella. So it's raining.", "FALSE", "Logic_Reasoning", "Hard", "Affirming consequent"),
    ("All birds have wings. Penguins are birds. So penguins have wings.", "TRUE", "Logic_Reasoning", "Hard", "Valid syllogism"),
    ("Some politicians lie. John is a politician. So John lies.", "FALSE", "Logic_Reasoning", "Hard", "Hasty generalization"),
    ("All mammals have fur. Whales are mammals. So whales have fur.", "FALSE", "Logic_Reasoning", "Hard", "False premise"),
    ("A is bigger than B. B is bigger than C. So A is bigger than C.", "TRUE", "Logic_Reasoning", "Hard", "Transitive property"),
    ("5 is more than 3. 3 is more than 1. So 5 is more than 1.", "TRUE", "Logic_Reasoning", "Hard", "Transitive property"),
    ("X is north of Y. Y is north of Z. So X is north of Z.", "TRUE", "Logic_Reasoning", "Hard", "Transitive relation"),
    ("Mary is taller than Sue. Sue is taller than Ann. So Mary is tallest.", "TRUE", "Logic_Reasoning", "Hard", "Transitive relation"),
    ("If no food, we die. We didn't die. So we had food.", "TRUE", "Logic_Reasoning", "Hard", "Modus tollens"),
    ("If it's a dog, it barks. This doesn't bark. So it's not a dog.", "TRUE", "Logic_Reasoning", "Hard", "Modus tollens"),
    ("All humans are mortal. Socrates is human. So Socrates is mortal.", "TRUE", "Logic_Reasoning", "Hard", "Classic valid syllogism"),
    ("Nothing is better than eternal happiness. A sandwich is better than nothing. So a sandwich is better than eternal happiness.", "FALSE", "Logic_Reasoning", "Hard", "Equivocation fallacy"),
    ("The sign says 'Fine for parking'. So it's fine to park here.", "FALSE", "Logic_Reasoning", "Hard", "Equivocation on 'fine'"),
    ("I saw a man on a hill with a telescope", "UNVERIFIED", "Ambiguous", "Hard", "Multiple interpretations"),
    ("Visiting relatives can be annoying", "UNVERIFIED", "Ambiguous", "Hard", "Syntactic ambiguity"),
    ("Time flies like an arrow", "UNVERIFIED", "Ambiguous", "Hard", "Metaphorical language"),
    ("I shot an elephant in my pajamas", "UNVERIFIED", "Ambiguous", "Hard", "Groucho Marx ambiguity"),
    ("The chicken is ready to eat", "UNVERIFIED", "Ambiguous", "Hard", "Who's eating?"),
    ("If God exists, who created God?", "UNVERIFIED", "Controversial", "Hard", "Theological question"),
    ("Is free will real or an illusion?", "UNVERIFIED", "Controversial", "Hard", "Philosophical debate"),
    ("Can machines be conscious?", "UNVERIFIED", "Controversial", "Hard", "AI consciousness"),
    ("Is abortion morally wrong?", "UNVERIFIED", "Controversial", "Hard", "Ethical question"),
    ("Should drugs be legalized?", "UNVERIFIED", "Controversial", "Hard", "Policy debate"),
    ("Is death penalty justified?", "UNVERIFIED", "Controversial", "Hard", "Ethical question"),
    ("Does life have inherent meaning?", "UNVERIFIED", "Controversial", "Hard", "Existential question"),
    ("Is capitalism better than socialism?", "UNVERIFIED", "Controversial", "Hard", "Economic systems"),
    ("Should we colonize Mars?", "UNVERIFIED", "Controversial", "Hard", "Space exploration ethics"),
    ("Is AI dangerous to humanity?", "UNVERIFIED", "Controversial", "Hard", "Technology risk"),
    ("Should we edit human genes?", "UNVERIFIED", "Controversial", "Hard", "Bioethics"),
    ("Do animals have rights?", "UNVERIFIED", "Controversial", "Hard", "Animal ethics"),
    ("Is eating meat ethical?", "UNVERIFIED", "Controversial", "Hard", "Dietary ethics"),
    ("Should we have borders?", "UNVERIFIED", "Controversial", "Hard", "Immigration policy"),
    ("Is taxation theft?", "UNVERIFIED", "Controversial", "Hard", "Political philosophy"),
    ("Should healthcare be free?", "UNVERIFIED", "Controversial", "Hard", "Healthcare policy"),
    ("Is privacy more important than security?", "UNVERIFIED", "Controversial", "Hard", "Rights balance"),
    ("Should we ban nuclear weapons?", "UNVERIFIED", "Controversial", "Hard", "Arms control"),
    ("Is democracy the best government?", "UNVERIFIED", "Controversial", "Hard", "Political systems"),
    ("Should we terraform other planets?", "UNVERIFIED", "Controversial", "Hard", "Planetary ethics"),
    ("Is climate change reversible?", "UNVERIFIED", "Scientific", "Medium", "Scientific uncertainty"),
    ("Will AI replace most jobs?", "UNVERIFIED", "Controversial", "Hard", "Future prediction"),
    ("Can we achieve immortality?", "UNVERIFIED", "Scientific", "Medium", "Biological limits"),
    ("Is faster-than-light travel possible?", "UNVERIFIED", "Scientific", "Medium", "Physics limits"),
    ("Do parallel universes exist?", "UNVERIFIED", "Scientific", "Medium", "Cosmological theory"),
    ("Is time travel possible?", "UNVERIFIED", "Scientific", "Medium", "Theoretical physics"),
    ("Did universe have a beginning?", "UNVERIFIED", "Scientific", "Medium", "Cosmological question"),
    ("Is there life on other planets?", "UNVERIFIED", "Scientific", "Medium", "Astrobiology"),
    ("Will humans go extinct?", "UNVERIFIED", "Scientific", "Medium", "Future prediction"),
    ("Can we reverse aging?", "UNVERIFIED", "Scientific", "Medium", "Biological research"),
    ("Is consciousness purely physical?", "UNVERIFIED", "Controversial", "Hard", "Mind-body problem"),
    ("Do we live in a simulation?", "UNVERIFIED", "Controversial", "Hard", "Simulation hypothesis"),
    ("Is reality objective?", "UNVERIFIED", "Controversial", "Hard", "Metaphysical question"),
    ("Does objective morality exist?", "UNVERIFIED", "Controversial", "Hard", "Meta-ethics"),
    ("Is mathematics discovered or invented?", "UNVERIFIED", "Controversial", "Hard", "Philosophy of math"),
    ("Can perfect justice exist?", "UNVERIFIED", "Controversial", "Hard", "Justice theory"),
    ("Is human nature good or evil?", "UNVERIFIED", "Controversial", "Hard", "Philosophical anthropology"),
    ("Do numbers really exist?", "UNVERIFIED", "Controversial", "Hard", "Mathematical platonism"),
    ("Is language necessary for thought?", "UNVERIFIED", "Controversial", "Hard", "Cognitive science"),
    ("Can animals think abstractly?", "UNVERIFIED", "Scientific", "Medium", "Comparative psychology"),
    ("Is beauty objective or subjective?", "UNVERIFIED", "Controversial", "Hard", "Aesthetics"),
    ("Do colors exist without observers?", "UNVERIFIED", "Controversial", "Hard", "Philosophy of perception"),
    ("Is happiness the meaning of life?", "UNVERIFIED", "Controversial", "Hard", "Existential question"),
    ("Can science answer all questions?", "UNVERIFIED", "Controversial", "Hard", "Scientism debate"),
    ("Is progress inevitable?", "UNVERIFIED", "Controversial", "Hard", "Philosophy of history"),
    ("Do abstract objects exist?", "UNVERIFIED", "Controversial", "Hard", "Ontological question"),
    ("Can we know anything for certain?", "UNVERIFIED", "Controversial", "Hard", "Epistemology"),
    ("Is solipsism refutable?", "UNVERIFIED", "Controversial", "Hard", "Philosophical skepticism"),
    ("Does the universe have a purpose?", "UNVERIFIED", "Controversial", "Hard", "Teleological question"),
    ("Is enlightenment achievable?", "UNVERIFIED", "Controversial", "Hard", "Spiritual question"),
    ("Can evil be justified?", "UNVERIFIED", "Controversial", "Hard", "Moral philosophy"),
    ("Is revenge ever justified?", "UNVERIFIED", "Controversial", "Hard", "Ethics of retribution"),
    ("Should we value equality or freedom more?", "UNVERIFIED", "Controversial", "Hard", "Political values"),
    ("Is patriotism a virtue?", "UNVERIFIED", "Controversial", "Hard", "Civic ethics"),
    ("Should art have moral limits?", "UNVERIFIED", "Controversial", "Hard", "Aesthetic ethics"),
    ("Is cultural relativism true?", "UNVERIFIED", "Controversial", "Hard", "Anthropological ethics"),
    ("Can we have knowledge without experience?", "UNVERIFIED", "Controversial", "Hard", "Rationalism vs empiricism"),
    ("Is determinism compatible with free will?", "UNVERIFIED", "Controversial", "Hard", "Compatibilism"),
    ("Should we preserve all languages?", "UNVERIFIED", "Controversial", "Hard", "Linguistic diversity"),
    ("Is tradition valuable in itself?", "UNVERIFIED", "Controversial", "Hard", "Cultural philosophy"),
    ("Can machines be creative?", "UNVERIFIED", "Controversial", "Hard", "AI creativity"),
    ("Is social progress real?", "UNVERIFIED", "Controversial", "Hard", "Sociology"),
    ("Should we edit human embryos?", "UNVERIFIED", "Controversial", "Hard", "CRISPR ethics"),
    ("Is inequality always bad?", "UNVERIFIED", "Controversial", "Hard", "Distributive justice"),
    ("Can war ever be just?", "UNVERIFIED", "Controversial", "Hard", "Just war theory"),
    ("Is censorship ever justified?", "UNVERIFIED", "Controversial", "Hard", "Free speech limits"),
    ("Should we extend human lifespan?", "UNVERIFIED", "Controversial", "Hard", "Longevity ethics"),
]

# BIOLOGY & MEDICINE (120 statements)
biology_claims = [
    ("DNA is shaped like a double helix", "TRUE", "Scientific", "Medium", "Watson-Crick model"),
    ("Cells are the basic unit of life", "TRUE", "Scientific", "Medium", "Cell theory"),
    ("Mitochondria produce energy", "TRUE", "Scientific", "Medium", "Cellular respiration"),
    ("Chloroplasts perform photosynthesis", "TRUE", "Scientific", "Medium", "Plant cells"),
    ("Bacteria are single-celled organisms", "TRUE", "Scientific", "Medium", "Microbiology"),
    ("Viruses are living organisms", "FALSE", "Scientific", "Medium", "Not cellular"),
    ("Antibiotics kill viruses", "FALSE", "Scientific", "Medium", "Only bacteria"),
    ("Vaccines contain dead viruses", "FALSE", "Scientific", "Medium", "Often weakened, not dead"),
    ("Blood type O is universal donor", "TRUE", "Scientific", "Medium", "Transfusion compatibility"),
    ("Humans have 206 bones as adults", "TRUE", "Scientific", "Medium", "Skeletal system"),
    # Continue with 110 more biology/medicine claims
    ("The heart has four chambers", "TRUE", "Scientific", "Medium", "Cardiac anatomy"),
    ("The brain uses most of body's energy", "FALSE", "Scientific", "Medium", "About 20%"),
    ("Neurons can regenerate easily", "FALSE", "Scientific", "Medium", "Limited regeneration"),
    ("The liver can regenerate", "TRUE", "Scientific", "Medium", "Unique organ property"),
    ("Kidneys filter blood", "TRUE", "Scientific", "Medium", "Renal function"),
    ("The appendix is completely useless", "FALSE", "Scientific", "Medium", "Immune function"),
    ("Tonsils serve no purpose", "FALSE", "Scientific", "Medium", "Part of immune system"),
    ("Wisdom teeth are vestigial", "TRUE", "Scientific", "Medium", "Evolutionary remnant"),
    ("Fingerprints are unique", "TRUE", "Scientific", "Medium", "Individual identification"),
    ("Identical twins have same DNA", "TRUE", "Scientific", "Medium", "Genetic identity"),
    ("Blood is red because of iron", "TRUE", "Scientific", "Medium", "Hemoglobin"),
    ("Veins carry blue blood", "FALSE", "Scientific", "Medium", "Blood is always red"),
    ("The tongue map is accurate", "FALSE", "Scientific", "Medium", "Taste buds everywhere"),
    ("Humans have only five senses", "FALSE", "Scientific", "Medium", "Many more senses"),
    ("The skin is the largest organ", "TRUE", "Scientific", "Medium", "Integumentary system"),
    ("Hair and nails are alive", "FALSE", "Scientific", "Medium", "Dead cells"),
    ("Goosebumps are vestigial", "TRUE", "Scientific", "Medium", "From fur-raising ancestors"),
    ("Hiccups serve no purpose", "TRUE", "Scientific", "Medium", "Vestigial reflex"),
    ("Yawning is contagious", "TRUE", "Scientific", "Medium", "Empathetic response"),
    ("Stretching prevents injuries", "FALSE", "Scientific", "Medium", "Warming up does"),
    ("Muscle turns to fat if you stop exercising", "FALSE", "Scientific", "Medium", "Different tissue types"),
    ("Lactic acid causes muscle soreness", "FALSE", "Scientific", "Medium", "Micro-tears cause soreness"),
    ("No pain, no gain is true", "FALSE", "Scientific", "Medium", "Pain signals injury"),
    ("Spot reduction of fat is possible", "FALSE", "Scientific", "Medium", "Can't target fat loss"),
    ("Metabolism slows drastically with age", "FALSE", "Scientific", "Medium", "Stays relatively stable"),
    ("Eating late causes weight gain", "FALSE", "Myths", "Medium", "Total calories matter"),
    ("Breakfast is the most important meal", "FALSE", "Myths", "Medium", "Personal preference"),
    ("Eating eggs raises cholesterol", "FALSE", "Scientific", "Medium", "Dietary cholesterol doesn't"),
    ("Fat makes you fat", "FALSE", "Scientific", "Medium", "Calories matter"),
    ("Carbs make you fat", "FALSE", "Scientific", "Medium", "Excess calories do"),
    ("Protein builds muscle", "TRUE", "Scientific", "Medium", "Muscle synthesis"),
    ("Gluten is bad for everyone", "FALSE", "Scientific", "Medium", "Only for celiac disease"),
    ("Dairy causes mucus", "FALSE", "Myths", "Medium", "No scientific evidence"),
    ("Sugar causes diabetes", "FALSE", "Scientific", "Medium", "Oversimplification"),
    ("Coffee stunts growth", "FALSE", "Myths", "Medium", "No evidence"),
    ("Drinking water flushes toxins", "FALSE", "Scientific", "Medium", "Kidneys do this normally"),
    ("Activated charcoal detoxifies", "FALSE", "Scientific", "Medium", "Not effective orally"),
    ("Cleanse diets work", "FALSE", "Scientific", "Medium", "No scientific support"),
    ("Superfoods exist", "FALSE", "Scientific", "Medium", "Marketing term"),
    ("Alkaline diet changes body pH", "FALSE", "Scientific", "Medium", "Body regulates pH"),
    ("Coconut oil is healthy", "FALSE", "Scientific", "Medium", "High saturated fat"),
    ("Apple cider vinegar aids weight loss", "FALSE", "Scientific", "Medium", "No strong evidence"),
    ("Green tea boosts metabolism", "FALSE", "Scientific", "Medium", "Minimal effect"),
    ("Probiotics cure gut problems", "FALSE", "Scientific", "Medium", "Limited evidence"),
    ("Multivitamins are necessary", "FALSE", "Scientific", "Medium", "Food provides nutrients"),
    ("Creatine is a steroid", "FALSE", "Scientific", "Medium", "Natural compound"),
    ("Protein powder is unhealthy", "FALSE", "Scientific", "Medium", "Just dried protein"),
    ("Soy feminizes men", "FALSE", "Scientific", "Medium", "Phytoestrogens differ"),
    ("MSG is neurotoxic", "FALSE", "Scientific", "Medium", "Safe in normal amounts"),
    ("Artificial sweeteners cause cancer", "FALSE", "Scientific", "Medium", "No strong evidence"),
    ("Microwaves destroy nutrients", "FALSE", "Scientific", "Medium", "All cooking affects nutrients"),
    ("Raw food is more nutritious", "FALSE", "Scientific", "Medium", "Cooking increases availability"),
    ("Freezing destroys nutrients", "FALSE", "Scientific", "Medium", "Preserves well"),
    ("Fresh is always better than frozen", "FALSE", "Scientific", "Medium", "Frozen can be fresher"),
    ("Organic food is pesticide-free", "FALSE", "Scientific", "Medium", "Uses organic pesticides"),
    ("GMOs are unnatural", "FALSE", "Scientific", "Medium", "Selective breeding is also unnatural"),
    ("Hormones in milk are dangerous", "FALSE", "Scientific", "Medium", "Digested in stomach"),
    ("Searing meat seals in juices", "FALSE", "Scientific", "Medium", "Maillard reaction"),
    ("Alcohol kills brain cells", "FALSE", "Scientific", "Medium", "Damages connections"),
    ("Weed is harmless", "FALSE", "Scientific", "Medium", "Has risks"),
    ("Nicotine causes cancer", "FALSE", "Scientific", "Medium", "Other chemicals in smoke do"),
    ("Vaping is completely safe", "FALSE", "Scientific", "Medium", "Long-term effects unknown"),
    ("Cannabis is not addictive", "FALSE", "Scientific", "Medium", "Can be psychologically addictive"),
    ("Psychedelics are always dangerous", "FALSE", "Scientific", "Medium", "Therapeutic potential"),
    ("Caffeine is highly addictive", "FALSE", "Scientific", "Medium", "Mild dependence"),
    ("Energy drinks are more caffeinated than coffee", "FALSE", "Scientific", "Medium", "Coffee usually higher"),
    ("Red Bull gives you wings", "FALSE", "Myths", "Medium", "Marketing slogan"),
    ("Sports drinks are necessary for exercise", "FALSE", "Scientific", "Medium", "Water sufficient for most"),
    ("Chocolate is toxic to humans", "FALSE", "Scientific", "Medium", "Toxic to dogs, not humans"),
    ("Poinsettias are deadly poisonous", "FALSE", "Myths", "Medium", "Mildly irritating"),
    ("Swallowing watermelon seeds grows plants in stomach", "FALSE", "Myths", "Medium", "Children's myth"),
    ("Double-dipping spreads bacteria", "TRUE", "Scientific", "Medium", "Hygiene issue"),
    ("Five-second rule is valid", "FALSE", "Scientific", "Medium", "Bacteria transfer instantly"),
    ("Washing hands with antibacterial soap is better", "FALSE", "Scientific", "Medium", "Regular soap sufficient"),
    ("Hand sanitizer is better than washing", "FALSE", "Scientific", "Medium", "Washing removes more"),
    ("You should feed a cold and starve a fever", "FALSE", "Myths", "Medium", "Eat and hydrate for both"),
    ("Vitamin C prevents colds", "FALSE", "Scientific", "Medium", "May reduce duration slightly"),
    ("Zinc prevents colds", "FALSE", "Scientific", "Medium", "May reduce duration"),
    ("Chicken soup cures colds", "FALSE", "Scientific", "Medium", "Provides comfort only"),
    ("Feed a fever, starve a cold", "FALSE", "Myths", "Medium", "Opposite of old saying"),
    ("Green mucus means bacterial infection", "FALSE", "Scientific", "Medium", "Color not diagnostic"),
    ("Going outside with wet hair causes colds", "FALSE", "Myths", "Medium", "Viruses cause colds"),
    ("Cold weather causes colds", "FALSE", "Myths", "Medium", "Indoor crowding does"),
    ("Flu shot gives you the flu", "FALSE", "Scientific", "Medium", "Contains inactivated virus"),
    ("Natural immunity is better than vaccine immunity", "FALSE", "Scientific", "Medium", "Vaccines safer"),
    ("Herd immunity prevents disease spread", "TRUE", "Scientific", "Medium", "Public health concept"),
    ("Masks don't work", "FALSE", "Scientific", "Medium", "Reduce transmission"),
    ("Social distancing prevents disease", "TRUE", "Scientific", "Medium", "Reduces contact"),
    ("Quarantine stops outbreaks", "TRUE", "Scientific", "Medium", "Isolation prevents spread"),
    ("Asymptomatic people can spread disease", "TRUE", "Scientific", "Medium", "Pre-symptomatic transmission"),
    ("COVID vaccine changes DNA", "FALSE", "Scientific", "Medium", "mRNA doesn't alter DNA"),
    ("COVID vaccine was rushed", "FALSE", "Scientific", "Medium", "Followed normal safety protocols"),
    ("COVID vaccine contains microchips", "FALSE", "Myths", "Medium", "Conspiracy theory"),
    ("5G causes COVID", "FALSE", "Myths", "Medium", "No biological mechanism"),
    ("Ivermectin cures COVID", "FALSE", "Scientific", "Medium", "No strong evidence"),
    ("Hydroxychloroquine cures COVID", "FALSE", "Scientific", "Medium", "No efficacy shown"),
    ("Sunlight kills COVID", "FALSE", "Scientific", "Medium", "UV damages virus but not treatment"),
    ("Bleach injection cures COVID", "FALSE", "Scientific", "Medium", "Extremely dangerous"),
    ("COVID came from a lab", "UNVERIFIED", "Controversial", "Hard", "Origin disputed"),
    ("COVID originated in bats", "UNVERIFIED", "Scientific", "Medium", "Likely but unconfirmed"),
    ("Pangolins were intermediate host", "UNVERIFIED", "Scientific", "Medium", "Hypothesis"),
    ("COVID is just the flu", "FALSE", "Scientific", "Medium", "Different virus, higher mortality"),
    ("Long COVID is real", "TRUE", "Scientific", "Medium", "Documented condition"),
    ("COVID affects young people minimally", "FALSE", "Scientific", "Medium", "Can affect all ages"),
]

# Combine all categories
all_new = []
all_new.extend(factual_claims)
all_new.extend(historical_claims)
all_new.extend(scientific_myths)
all_new.extend(logic_claims)
all_new.extend(biology_claims)

# Number them starting from 361
for i, claim in enumerate(all_new, start=361):
    new_statements.append({
        'test_id': str(i),
        'category': claim[2],
        'difficulty': claim[3],
        'statement': claim[0],
        'expected_verdict': claim[1],
        'reasoning': claim[4]
    })

# Combine with existing
combined = existing + new_statements[:640]

# Save
output_file = 'test_statements_1000.csv'
with open(output_file, 'w', newline='', encoding='utf-8') as f:
    fieldnames = ['test_id', 'category', 'difficulty', 'statement', 'expected_verdict', 'reasoning']
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(combined)

print(f"✅ Generated {len(new_statements)} new statements")
print(f"✅ Total statements: {len(combined)}")
print(f"✅ Saved to {output_file}")
